### ISSUE TITLE
Support Querying

### ISSUE THREAD

**Issue by ArmanKamal** [ArmanKamal/DatabaseProject#4]
Given a department:
   List all its program
   List all its faculty (including what program each faculty is in charge of, if there is one)
Given a program:
   List all the courses, together with the objectives/sub-objectives association with
  year
   List all the objectives
o Given a semester and a program:
   List all the evaluation results for each section. (If data for some sections has not
  been entered, just indicate that the information is not found)
o Given an academic year (e.g. 23-24, which constitute summer 23, fall 23 and spring 24)
   List all the evaluation results for each objective/sub-objective
• For each objective/sub-objective, list the course/section that are involved in evaluating them, and list the result for each course/section.
• For each objective/sub-objective, aggregate the result to show the number (and the percentage) of students

**Comment by S-Bryce** [comment]
Redundant with #2 #3 #6 & #7
